### PR TITLE
Httpclient headers

### PR DESCRIPTION
**Pull request by harnash**
Added possibility to modify headers when sending requests through ApiClient.

@Wikia/services-team

### CODE REVIEW

**Comment by drsnyder** [comment]
I wonder if we should start using a 3rd part HTTP client in helios. It looks like there are a few that have a decent commit history. See https://github.com/parnurzeal/gorequest as an example.

To me this falls in the general utility category and someone has probably done it already and better than we will since it's not our primary focus. Thoughts?

**Comment by harnash** [comment]
Looks nice, this one is also good: https://github.com/franela/goreq (additionally has JSON deserialization)

**Comment by ArturKlajnerok** [comment]
@harnash Lgtm :+1:

**Comment by drsnyder** [comment]
`goreq` also looks nice. Should we ease into one in the tests and consider the go-commons one deprecated?

**Comment by harnash** [comment]
+1

**Comment by ArturKlajnerok** [comment]
I've created https://wikia-inc.atlassian.net/browse/SERVICES-674 to address 3rd part HTTP client usage.

**Pull request merged**
